name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - prod
    paths:
      - 'environments/**'
      - 'modules/**'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: environments/${{ github.ref_name }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan
        working-directory: environments/${{ github.ref_name }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/prod'
        run: terraform apply -auto-approve
        working-directory: environments/${{ github.ref_name }}